
title: My Resume
url: ''
baseurl: '' #change it according to your repository name



# Profile information
yourname: Nazmus Shakib  ## put your name
title: 'Software Engineer @ cloudly.io'  ## your title
location: Dhaka, Bangladesh


## Social Profiles
facebook: http://www.facebook.com/shuvo.dunia  ## your facebook account url
twitter: https://twitter.com/SHUVO_DUNIA  ## your twitter account url
linkedin: http://www.linkedin.com/in/nshakib  ## your linkedin account url
github: https://github.com/NazmusShakib/  ## you dribbble account url
stack-overflow: https://stackoverflow.com/users/7633321/nazmus-shakib  ## your stack-overflow account url



# Update all the sections by editing the files inside _includes folder.
